### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by kim** [bbqsrc/raunch#1]
Do you have a working example for this? I get `ESRCH` no matter what.

**Comment by kim** [comment]
Okay, nevermind. It turns out that a. the `.plist` MUST be in the appropriate directory (eg. `~/Library/LaunchAgents`), and b. the `UserName` property MUST be set in the `.plist`.

**Comment by bbqsrc** [comment]
Yeah, it's a single function thing. All the other requirements are the same as the C documentation. :)

**Comment by bbqsrc** [comment]
@kim real world example of how I use this: https://github.com/divvun/pahkat/blob/3ca598d96f2ee7385f0053e5faee8763792aa363/pahkat-rpc/src/lib.rs#L840-L856

**Comment by kim** [comment]
Thanks. The confusing part was that `launchd.plist(5)` doesn't mention that both conditions in https://github.com/bbqsrc/raunch/issues/1#issuecomment-1086584766 must be met; otherwise the service will be run, but the socket is not available. Since that doesn't seem to make much sense, I'd assume it's a bug in `launchd`.

**Comment by bbqsrc** [comment]
launchd hates us.

Here is our launchd file at `/Library/LaunchDaemons/no.divvun.pahkatd.plist`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>RUST_LOG</key>
		<string>pahkat_rpc=trace,pahkat_client=trace</string>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>no.divvun.pahkatd</string>
	<key>OnDemand</key>
	<false/>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/Divvun Manager.app/Contents/MacOS/pahkatd</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>Sockets</key>
	<dict>
		<key>pahkat</key>
		<dict>
			<key>SecureSocketWithKey</key>
			<string>PAHKATD_UDS_PATH</string>
			<key>SockFamily</key>
			<string>Unix</string>
		</dict>
	</dict>
	<key>StandardErrorPath</key>
	<string>/Library/Logs/Pahkat/stderr.log</string>
	<key>StandardOutPath</key>
	<string>/Library/Logs/Pahkat/stdout.log</string>
</dict>
</plist>
```

**Comment by kim** [comment]
Ahaha, amazing. I‘m sure a combinatorial search would yield other working configurations 😂
